# Change these first
owner: mamonakucommittee # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: JeremieBerduck.com
    url: https://jeremieberduck.com
    icon: https://jeremieberduck.com/user/themes/jeremie-berduck-com/images/favicon/apple-touch-icon.png
  - name: Shoobie.app
    url: https://shoobie.app
    icon: https://shoobie.app/user/themes/shoobie/images/favicons/apple-touch-icon.png
  - name: Mamonaku.io
    url: https://mamonaku.io
  - name: World Tides API
    url: https://www.worldtides.info/api/v2?extremes&lat=52.370216&lon=4.895168&key=$API_WORLD_TIDE&date=today
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: World Weather Online API
    url: https://api.worldweatheronline.com/premium/v1/marine.ashx?key=$API_WORLD_WEATHER_ONLINE&q=52.370216,4.895168&tide=no&fx=yes&tp=1&format=json
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Open Weather API
    url: https://api.openweathermap.org/data/2.5/uvi?appid=$API_OPEN_WEATHER&lat=52.370216&lon=4.895168
    expectedStatusCodes:
      - 200
      - 201
      - 404

assignees: # Users to assign downtime issues (optional)
  - jeremieb

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://raw.githubusercontent.com/MamonakuCommittee/status/master/mamonaku-logo-1035.png
  name: Mamonaku Status
  introTitle: "**Mamonaku Committee Status**"
  #introMessage: This status page is powered by [Uptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
